// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         username: "Major Nelson"
 *     }
 */
export interface ProfileXboxRequest {
    /** The Xbox username. */
    username: string;
}
