// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         link: "https://vm.tiktok.com/ZMexample/"
 *     }
 */
export interface ResolveShareLinkTiktokRequest {
    /** A TikTok share link. `url` or `query` are accepted as well. */
    link: string;
}
