// This file was auto-generated by Fern from our API Definition.

import type * as OsintCat from "../../../../index.js";

/**
 * @example
 *     {
 *         query: "Notch",
 *         type: "username"
 *     }
 */
export interface LeaksMinecraftRequest {
    /** The value to search for. */
    query: string;
    /** One of `username`, `uuid`, `email`, `ip`, `password`. */
    type: OsintCat.LeaksMinecraftRequestType;
}
