// This file was auto-generated by Fern from our API Definition.

import type * as OsintCat from "../../../../index.js";

/**
 * @example
 *     {
 *         query: "Notch"
 *     }
 */
export interface PlayerMinecraftRequest {
    /** A Minecraft username (or the value matching `type`). */
    query: string;
    /** What `query` is for the leak search: `username` (default), `uuid`, `email` or `ip`. */
    type?: OsintCat.PlayerMinecraftRequestType;
}
