// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         username: "Notch"
 *     }
 */
export interface ProfileMinecraftRequest {
    /** The Minecraft username. */
    username: string;
}
