// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         username: "gaben"
 *     }
 */
export interface ProfileSteamRequest {
    /** The Steam username. */
    username: string;
}
