// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         query: "hikaru"
 *     }
 */
export interface LookupChessRequest {
    /** A Chess.com username or an e-mail address. */
    query: string;
}
