// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         machine_id: "machine_id"
 *     }
 */
export interface DownloadMachineMachineViewerRequest {
    /** Machine ID (a UUID), from `machineViewer.search`. */
    machine_id: string;
}
