// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         file_id: "file_id"
 *     }
 */
export interface DownloadFileMachineViewerRequest {
    /** File ID, from `machineViewer.files`. */
    file_id: string;
}
