// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         file_id: "aB3dE5fG7hI9jK1lM3nO"
 *     }
 */
export interface FileMachineViewerRequest {
    /** File ID, from `machineViewer.files`. */
    file_id: string;
}
