// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         machine_id: "742e1f66-f449-4a6c-80d5-8f5eb8e9c2b5"
 *     }
 */
export interface FilesMachineViewerRequest {
    /** Machine ID (a UUID), from `machineViewer.search`. */
    machine_id: string;
}
