// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         query: "DESKTOP"
 *     }
 */
export interface SearchMachineViewerRequest {
    /** What to search for: a name, username, hostname or machine ID. */
    query: string;
}
