// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         query: "jack"
 *     }
 */
export interface ProfileXRequest {
    /** The X username, with or without `@`. */
    query: string;
}
