// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         username: "xqc"
 *     }
 */
export interface ProfileTwitchRequest {
    /** The Twitch username. */
    username: string;
}
