// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         query: "example.com,osintcat.net"
 *     }
 */
export interface ResolveDnsRequest {
    /** A hostname, or several separated by commas. */
    query: string;
}
