// This file was auto-generated by Fern from our API Definition.

import type * as OsintCat from "../../../../index.js";

/**
 * @example
 *     {
 *         query: "user@example.com"
 *     }
 */
export interface DatabaseSearchBreachRequest {
    /** The e-mail address or domain. */
    query: string;
    /** `email` or `domain`. Detected from `query` when left out. */
    type?: OsintCat.DatabaseSearchBreachRequestType;
}
