// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         query: "example.com"
 *     }
 */
export interface DomainBreachRequest {
    /** The domain, e.g. `example.com`. */
    query: string;
}
