// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         query: "user@example.com"
 *     }
 */
export interface SearchBreachRequest {
    /** What to search for: an e-mail address, username, domain, phone number, IP address, name or password. */
    query: string;
}
