// This file was auto-generated by Fern from our API Definition.

export const DatabaseSearchBreachRequestType = {
    Email: "email",
    Domain: "domain",
} as const;
export type DatabaseSearchBreachRequestType =
    (typeof DatabaseSearchBreachRequestType)[keyof typeof DatabaseSearchBreachRequestType];
