// This file was auto-generated by Fern from our API Definition.

import type { BaseClientOptions, BaseRequestOptions } from "../../../../BaseClient.js";
import { type NormalizedClientOptionsWithAuth, normalizeClientOptionsWithAuth } from "../../../../BaseClient.js";
import { mergeHeaders } from "../../../../core/headers.js";
import * as core from "../../../../core/index.js";
import * as environments from "../../../../environments.js";
import { handleNonStatusCodeError } from "../../../../errors/handleNonStatusCodeError.js";
import * as errors from "../../../../errors/index.js";
import * as OsintCat from "../../../index.js";

export declare namespace MachineViewerClient {
    export type Options = BaseClientOptions;

    export interface RequestOptions extends BaseRequestOptions {}
}

export class MachineViewerClient {
    protected readonly _options: NormalizedClientOptionsWithAuth<MachineViewerClient.Options>;

    constructor(options: MachineViewerClient.Options = {}) {
        this._options = normalizeClientOptionsWithAuth(options);
    }

    /**
     * How many machines, files, passwords, tokens, cookies and payment cards the Machine Viewer holds.
     *
     * Every Machine Viewer request counts as one lookup against your plan's daily allowance (Max: unlimited). When the allowance is used up, requests can continue at a per-lookup price charged to your balance; a search that finds nothing is not charged.
     *
     * Docs: https://docs.osintcat.net/api-reference/endpoint/machine-viewer
     *
     * @param {MachineViewerClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link OsintCat.BadRequestError}
     * @throws {@link OsintCat.UnauthorizedError}
     * @throws {@link OsintCat.ForbiddenError}
     * @throws {@link OsintCat.TooManyRequestsError}
     *
     * @example
     *     await client.machineViewer.stats()
     */
    public stats(
        requestOptions?: MachineViewerClient.RequestOptions,
    ): core.HttpResponsePromise<OsintCat.MachineViewerStats> {
        return core.HttpResponsePromise.fromPromise(this.__stats(requestOptions));
    }

    private async __stats(
        requestOptions?: MachineViewerClient.RequestOptions,
    ): Promise<core.WithRawResponse<OsintCat.MachineViewerStats>> {
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.OsintCatEnvironment.Production,
                "api/machine_viewer/stats",
            ),
            method: "GET",
            headers: _headers,
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as OsintCat.MachineViewerStats, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new OsintCat.BadRequestError(_response.error.body as OsintCat.Error, _response.rawResponse);
                case 401:
                    throw new OsintCat.UnauthorizedError(_response.error.body as OsintCat.Error, _response.rawResponse);
                case 403:
                    throw new OsintCat.ForbiddenError(_response.error.body as OsintCat.Error, _response.rawResponse);
                case 429:
                    throw new OsintCat.TooManyRequestsError(
                        _response.error.body as OsintCat.Error,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.OsintCatError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "GET", "/api/machine_viewer/stats");
    }

    /**
     * Searches machines by name, username, hostname or machine ID.
     *
     * Every Machine Viewer request counts as one lookup against your plan's daily allowance (Max: unlimited). When the allowance is used up, requests can continue at a per-lookup price charged to your balance; a search that finds nothing is not charged.
     *
     * Docs: https://docs.osintcat.net/api-reference/endpoint/machine-viewer
     *
     * @param {OsintCat.SearchMachineViewerRequest} request
     * @param {MachineViewerClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link OsintCat.BadRequestError}
     * @throws {@link OsintCat.UnauthorizedError}
     * @throws {@link OsintCat.ForbiddenError}
     * @throws {@link OsintCat.TooManyRequestsError}
     *
     * @example
     *     await client.machineViewer.search({
     *         query: "DESKTOP"
     *     })
     */
    public search(
        request: OsintCat.SearchMachineViewerRequest,
        requestOptions?: MachineViewerClient.RequestOptions,
    ): core.HttpResponsePromise<OsintCat.MachineSearchResponse> {
        return core.HttpResponsePromise.fromPromise(this.__search(request, requestOptions));
    }

    private async __search(
        request: OsintCat.SearchMachineViewerRequest,
        requestOptions?: MachineViewerClient.RequestOptions,
    ): Promise<core.WithRawResponse<OsintCat.MachineSearchResponse>> {
        const { query } = request;
        const _queryParams: Record<string, unknown> = {
            query,
        };
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.OsintCatEnvironment.Production,
                "api/machine_viewer/search",
            ),
            method: "GET",
            headers: _headers,
            queryString: core.url
                .queryBuilder()
                .addMany(_queryParams)
                .mergeAdditional(requestOptions?.queryParams)
                .build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as OsintCat.MachineSearchResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new OsintCat.BadRequestError(_response.error.body as OsintCat.Error, _response.rawResponse);
                case 401:
                    throw new OsintCat.UnauthorizedError(_response.error.body as OsintCat.Error, _response.rawResponse);
                case 403:
                    throw new OsintCat.ForbiddenError(_response.error.body as OsintCat.Error, _response.rawResponse);
                case 429:
                    throw new OsintCat.TooManyRequestsError(
                        _response.error.body as OsintCat.Error,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.OsintCatError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "GET", "/api/machine_viewer/search");
    }

    /**
     * One machine, with the e-mail addresses and tokens found on it.
     *
     * Every Machine Viewer request counts as one lookup against your plan's daily allowance (Max: unlimited). When the allowance is used up, requests can continue at a per-lookup price charged to your balance; a search that finds nothing is not charged.
     *
     * Docs: https://docs.osintcat.net/api-reference/endpoint/machine-viewer
     *
     * @param {OsintCat.MachineMachineViewerRequest} request
     * @param {MachineViewerClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link OsintCat.BadRequestError}
     * @throws {@link OsintCat.UnauthorizedError}
     * @throws {@link OsintCat.ForbiddenError}
     * @throws {@link OsintCat.NotFoundError}
     * @throws {@link OsintCat.TooManyRequestsError}
     *
     * @example
     *     await client.machineViewer.machine({
     *         machine_id: "742e1f66-f449-4a6c-80d5-8f5eb8e9c2b5"
     *     })
     */
    public machine(
        request: OsintCat.MachineMachineViewerRequest,
        requestOptions?: MachineViewerClient.RequestOptions,
    ): core.HttpResponsePromise<OsintCat.MachineInfoResponse> {
        return core.HttpResponsePromise.fromPromise(this.__machine(request, requestOptions));
    }

    private async __machine(
        request: OsintCat.MachineMachineViewerRequest,
        requestOptions?: MachineViewerClient.RequestOptions,
    ): Promise<core.WithRawResponse<OsintCat.MachineInfoResponse>> {
        const { machine_id: machineId } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.OsintCatEnvironment.Production,
                `api/machine_viewer/machines/${core.url.encodePathParam(machineId)}/info`,
            ),
            method: "GET",
            headers: _headers,
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as OsintCat.MachineInfoResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new OsintCat.BadRequestError(_response.error.body as OsintCat.Error, _response.rawResponse);
                case 401:
                    throw new OsintCat.UnauthorizedError(_response.error.body as OsintCat.Error, _response.rawResponse);
                case 403:
                    throw new OsintCat.ForbiddenError(_response.error.body as OsintCat.Error, _response.rawResponse);
                case 404:
                    throw new OsintCat.NotFoundError(_response.error.body as OsintCat.Error, _response.rawResponse);
                case 429:
                    throw new OsintCat.TooManyRequestsError(
                        _response.error.body as OsintCat.Error,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.OsintCatError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "GET",
            "/api/machine_viewer/machines/{machine_id}/info",
        );
    }

    /**
     * Every file of a machine, with its path and size. Use a file's `id` with `machineViewer.file`.
     *
     * Every Machine Viewer request counts as one lookup against your plan's daily allowance (Max: unlimited). When the allowance is used up, requests can continue at a per-lookup price charged to your balance; a search that finds nothing is not charged.
     *
     * Docs: https://docs.osintcat.net/api-reference/endpoint/machine-viewer
     *
     * @param {OsintCat.FilesMachineViewerRequest} request
     * @param {MachineViewerClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link OsintCat.BadRequestError}
     * @throws {@link OsintCat.UnauthorizedError}
     * @throws {@link OsintCat.ForbiddenError}
     * @throws {@link OsintCat.NotFoundError}
     * @throws {@link OsintCat.TooManyRequestsError}
     *
     * @example
     *     await client.machineViewer.files({
     *         machine_id: "742e1f66-f449-4a6c-80d5-8f5eb8e9c2b5"
     *     })
     */
    public files(
        request: OsintCat.FilesMachineViewerRequest,
        requestOptions?: MachineViewerClient.RequestOptions,
    ): core.HttpResponsePromise<OsintCat.MachineFilesResponse> {
        return core.HttpResponsePromise.fromPromise(this.__files(request, requestOptions));
    }

    private async __files(
        request: OsintCat.FilesMachineViewerRequest,
        requestOptions?: MachineViewerClient.RequestOptions,
    ): Promise<core.WithRawResponse<OsintCat.MachineFilesResponse>> {
        const { machine_id: machineId } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.OsintCatEnvironment.Production,
                `api/machine_viewer/machines/${core.url.encodePathParam(machineId)}/files/treeview`,
            ),
            method: "GET",
            headers: _headers,
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as OsintCat.MachineFilesResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new OsintCat.BadRequestError(_response.error.body as OsintCat.Error, _response.rawResponse);
                case 401:
                    throw new OsintCat.UnauthorizedError(_response.error.body as OsintCat.Error, _response.rawResponse);
                case 403:
                    throw new OsintCat.ForbiddenError(_response.error.body as OsintCat.Error, _response.rawResponse);
                case 404:
                    throw new OsintCat.NotFoundError(_response.error.body as OsintCat.Error, _response.rawResponse);
                case 429:
                    throw new OsintCat.TooManyRequestsError(
                        _response.error.body as OsintCat.Error,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.OsintCatError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "GET",
            "/api/machine_viewer/machines/{machine_id}/files/treeview",
        );
    }

    /**
     * One file, with its content as text.
     *
     * Every Machine Viewer request counts as one lookup against your plan's daily allowance (Max: unlimited). When the allowance is used up, requests can continue at a per-lookup price charged to your balance; a search that finds nothing is not charged.
     *
     * Docs: https://docs.osintcat.net/api-reference/endpoint/machine-viewer
     *
     * @param {OsintCat.FileMachineViewerRequest} request
     * @param {MachineViewerClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link OsintCat.BadRequestError}
     * @throws {@link OsintCat.UnauthorizedError}
     * @throws {@link OsintCat.ForbiddenError}
     * @throws {@link OsintCat.NotFoundError}
     * @throws {@link OsintCat.TooManyRequestsError}
     *
     * @example
     *     await client.machineViewer.file({
     *         file_id: "aB3dE5fG7hI9jK1lM3nO"
     *     })
     */
    public file(
        request: OsintCat.FileMachineViewerRequest,
        requestOptions?: MachineViewerClient.RequestOptions,
    ): core.HttpResponsePromise<OsintCat.MachineFileResponse> {
        return core.HttpResponsePromise.fromPromise(this.__file(request, requestOptions));
    }

    private async __file(
        request: OsintCat.FileMachineViewerRequest,
        requestOptions?: MachineViewerClient.RequestOptions,
    ): Promise<core.WithRawResponse<OsintCat.MachineFileResponse>> {
        const { file_id: fileId } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.OsintCatEnvironment.Production,
                `api/machine_viewer/files/${core.url.encodePathParam(fileId)}/info`,
            ),
            method: "GET",
            headers: _headers,
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as OsintCat.MachineFileResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new OsintCat.BadRequestError(_response.error.body as OsintCat.Error, _response.rawResponse);
                case 401:
                    throw new OsintCat.UnauthorizedError(_response.error.body as OsintCat.Error, _response.rawResponse);
                case 403:
                    throw new OsintCat.ForbiddenError(_response.error.body as OsintCat.Error, _response.rawResponse);
                case 404:
                    throw new OsintCat.NotFoundError(_response.error.body as OsintCat.Error, _response.rawResponse);
                case 429:
                    throw new OsintCat.TooManyRequestsError(
                        _response.error.body as OsintCat.Error,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.OsintCatError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "GET",
            "/api/machine_viewer/files/{file_id}/info",
        );
    }

    /**
     * The file itself, as it was in the log.
     *
     * Every Machine Viewer request counts as one lookup against your plan's daily allowance (Max: unlimited). When the allowance is used up, requests can continue at a per-lookup price charged to your balance; a search that finds nothing is not charged.
     *
     * Docs: https://docs.osintcat.net/api-reference/endpoint/machine-viewer
     *
     * @throws {@link OsintCat.BadRequestError}
     * @throws {@link OsintCat.UnauthorizedError}
     * @throws {@link OsintCat.ForbiddenError}
     * @throws {@link OsintCat.NotFoundError}
     * @throws {@link OsintCat.TooManyRequestsError}
     */
    public downloadFile(
        request: OsintCat.DownloadFileMachineViewerRequest,
        requestOptions?: MachineViewerClient.RequestOptions,
    ): core.HttpResponsePromise<core.BinaryResponse> {
        return core.HttpResponsePromise.fromPromise(this.__downloadFile(request, requestOptions));
    }

    private async __downloadFile(
        request: OsintCat.DownloadFileMachineViewerRequest,
        requestOptions?: MachineViewerClient.RequestOptions,
    ): Promise<core.WithRawResponse<core.BinaryResponse>> {
        const { file_id: fileId } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher<core.BinaryResponse>({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.OsintCatEnvironment.Production,
                `api/machine_viewer/files/${core.url.encodePathParam(fileId)}/download`,
            ),
            method: "GET",
            headers: _headers,
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            responseType: "binary-response",
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new OsintCat.BadRequestError(_response.error.body as OsintCat.Error, _response.rawResponse);
                case 401:
                    throw new OsintCat.UnauthorizedError(_response.error.body as OsintCat.Error, _response.rawResponse);
                case 403:
                    throw new OsintCat.ForbiddenError(_response.error.body as OsintCat.Error, _response.rawResponse);
                case 404:
                    throw new OsintCat.NotFoundError(_response.error.body as OsintCat.Error, _response.rawResponse);
                case 429:
                    throw new OsintCat.TooManyRequestsError(
                        _response.error.body as OsintCat.Error,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.OsintCatError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "GET",
            "/api/machine_viewer/files/{file_id}/download",
        );
    }

    /**
     * Every file of a machine in one ZIP archive.
     *
     * Every Machine Viewer request counts as one lookup against your plan's daily allowance (Max: unlimited). When the allowance is used up, requests can continue at a per-lookup price charged to your balance; a search that finds nothing is not charged.
     *
     * Docs: https://docs.osintcat.net/api-reference/endpoint/machine-viewer
     *
     * @throws {@link OsintCat.BadRequestError}
     * @throws {@link OsintCat.UnauthorizedError}
     * @throws {@link OsintCat.ForbiddenError}
     * @throws {@link OsintCat.NotFoundError}
     * @throws {@link OsintCat.TooManyRequestsError}
     */
    public downloadMachine(
        request: OsintCat.DownloadMachineMachineViewerRequest,
        requestOptions?: MachineViewerClient.RequestOptions,
    ): core.HttpResponsePromise<core.BinaryResponse> {
        return core.HttpResponsePromise.fromPromise(this.__downloadMachine(request, requestOptions));
    }

    private async __downloadMachine(
        request: OsintCat.DownloadMachineMachineViewerRequest,
        requestOptions?: MachineViewerClient.RequestOptions,
    ): Promise<core.WithRawResponse<core.BinaryResponse>> {
        const { machine_id: machineId } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher<core.BinaryResponse>({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.OsintCatEnvironment.Production,
                `api/machine_viewer/machines/${core.url.encodePathParam(machineId)}/download`,
            ),
            method: "GET",
            headers: _headers,
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            responseType: "binary-response",
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new OsintCat.BadRequestError(_response.error.body as OsintCat.Error, _response.rawResponse);
                case 401:
                    throw new OsintCat.UnauthorizedError(_response.error.body as OsintCat.Error, _response.rawResponse);
                case 403:
                    throw new OsintCat.ForbiddenError(_response.error.body as OsintCat.Error, _response.rawResponse);
                case 404:
                    throw new OsintCat.NotFoundError(_response.error.body as OsintCat.Error, _response.rawResponse);
                case 429:
                    throw new OsintCat.TooManyRequestsError(
                        _response.error.body as OsintCat.Error,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.OsintCatError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "GET",
            "/api/machine_viewer/machines/{machine_id}/download",
        );
    }
}
