// This file was auto-generated by Fern from our API Definition.

export const LeaksMinecraftRequestType = {
    Username: "username",
    Uuid: "uuid",
    Email: "email",
    Ip: "ip",
    Password: "password",
} as const;
export type LeaksMinecraftRequestType = (typeof LeaksMinecraftRequestType)[keyof typeof LeaksMinecraftRequestType];
