// This file was auto-generated by Fern from our API Definition.

export const PlayerMinecraftRequestType = {
    Username: "username",
    Uuid: "uuid",
    Email: "email",
    Ip: "ip",
} as const;
export type PlayerMinecraftRequestType = (typeof PlayerMinecraftRequestType)[keyof typeof PlayerMinecraftRequestType];
