// This file was auto-generated by Fern from our API Definition.

import type * as OsintCat from "../index.js";

export interface BreachResponse {
    /** Always `OsintCat`. */
    api?: string | undefined;
    /** Time the search took, in milliseconds. */
    elapsed_ms?: number | undefined;
    /** When the search ran (UTC), e.g. `Oct 6th 09:41`. */
    timestamp?: string | undefined;
    /** Number of records in `breach_data`. */
    results_count?: number | undefined;
    /** Matching records. The fields of a record depend on the breach it comes from (for example `email`, `username`, `password`, `hash`, `ip`, `name`, `phone`); `source_db` names the breach or index the record was found in. */
    breach_data?: unknown[] | undefined;
    _meta?: OsintCat.UsageMeta | undefined;
    /** Accepts any additional properties */
    [key: string]: any;
}
