// This file was auto-generated by Fern from our API Definition.

export interface ChessResponse {
    /** `true` when the lookup ran. */
    success?: boolean | undefined;
    /** Whether anything was found. */
    found?: boolean | undefined;
    /** The query. */
    query?: string | undefined;
    /** The username the lookup settled on. */
    resolved_username?: string | undefined;
    /** The public profile (name, country, joined, last online, followers ...), or `null`. */
    live_profile?: Record<string, unknown> | undefined;
    /** Ratings: `rapid`, `blitz`, `bullet`, `fide` (each `null` when unrated). */
    live_stats?: Record<string, unknown> | undefined;
    /** Up to 10 clubs. */
    live_clubs?: unknown[] | undefined;
    /** Records from the Chess.com leak. */
    leak_records?: unknown[] | undefined;
    /** Number of leak records. */
    leak_count?: number | undefined;
    /** Accepts any additional properties */
    [key: string]: any;
}
