// This file was auto-generated by Fern from our API Definition.

/**
 * The matching people (RUT, full name and the public record details available for them). Results are cached for an hour.
 */
export type ChileanNameResponse = unknown;
