// This file was auto-generated by Fern from our API Definition.

/**
 * The vehicle and its registered owner details as available. An empty object when nothing was found. Results are cached for an hour.
 */
export type ChileanCarResponse = unknown;
