// This file was auto-generated by Fern from our API Definition.

export interface DatabaseSearchResponse {
    /** Matching entries (typically a URL, login and password, and when it was collected). */
    results?: unknown[] | undefined;
    /** Number of entries. */
    results_count?: number | undefined;
    /** The query searched for. */
    query?: string | undefined;
    /** `email` or `domain`. */
    type?: string | undefined;
    /** Time the search took. */
    execution_time?: string | undefined;
    /** `success`. */
    status?: string | undefined;
    /** Accepts any additional properties */
    [key: string]: any;
}
