// This file was auto-generated by Fern from our API Definition.

/**
 * An object mapping each hostname to its IP address (`null` when it does not resolve).
 */
export type DnsResolverResponse = Record<string, string>;
