// This file was auto-generated by Fern from our API Definition.

/**
 * An array of breach records. The fields of a record depend on the breach it comes from.
 */
export type DomainResponse = Record<string, unknown>[];
