// This file was auto-generated by Fern from our API Definition.

export interface EmailOsintResults {
    /** Services the address is registered with. */
    register?: unknown[] | undefined;
    /** Breaches the address appears in. */
    breach?: unknown[] | undefined;
    /** Further findings from service lookups (profile names, pictures, account details). */
    api?: unknown[] | undefined;
    /** Accepts any additional properties */
    [key: string]: any;
}
