// This file was auto-generated by Fern from our API Definition.

import type * as OsintCat from "../index.js";

/**
 * Results for the same address may come from a cache for up to 15 minutes.
 */
export interface EmailOsintResponse {
    results?: OsintCat.EmailOsintResults | undefined;
    _meta?: OsintCat.UsageMeta | undefined;
    /** Accepts any additional properties */
    [key: string]: any;
}
