// This file was auto-generated by Fern from our API Definition.

/**
 * What every error response carries. `error` is a short code or message; some errors add more fields (`error_id`, `code`, `allowed_types`).
 */
export interface Error {
    error?: string | undefined;
    message?: string | undefined;
    /** Quote it to support. */
    error_id?: string | undefined;
    code?: string | undefined;
    /** Accepts any additional properties */
    [key: string]: any;
}
