// This file was auto-generated by Fern from our API Definition.

export interface GithubExtraData {
    /** Login. */
    Username?: string | undefined;
    /** Name. */
    Name?: string | undefined;
    /** Bio. */
    Bio?: string | undefined;
    /** Location. */
    Location?: string | undefined;
    /** Company. */
    Company?: string | undefined;
    /** Website. */
    Blog?: string | undefined;
    /** Public e-mail. */
    Email?: string | undefined;
    /** X/Twitter handle. */
    Twitter?: string | undefined;
    /** Followers. */
    Followers?: number | undefined;
    /** Following. */
    Following?: number | undefined;
    /** Public repositories. */
    PublicRepos?: number | undefined;
    /** Account creation. */
    CreatedAt?: string | undefined;
    /** Profile link. */
    ProfileUrl?: string | undefined;
    /** The 10 most recently pushed repositories (name, description, url, language, stars, forks). */
    Repositories?: unknown[] | undefined;
    /** Accepts any additional properties */
    [key: string]: any;
}
