// This file was auto-generated by Fern from our API Definition.

import type * as OsintCat from "../index.js";

/**
 * `taken` is `true` when the account exists. `ExtraData` holds what the profile shows publicly; a field the profile does not have is left out. When the lookup could not be completed, `taken` is `false` and `error` says why (for example `rate_limited`, try again later).
 */
export interface GithubResponse {
    /** Whether an account with this username exists. */
    taken?: boolean | undefined;
    /** Present only when the lookup could not be completed. */
    error?: string | undefined;
    ExtraData?: OsintCat.GithubExtraData | undefined;
    /** Accepts any additional properties */
    [key: string]: any;
}
