// This file was auto-generated by Fern from our API Definition.

import type * as OsintCat from "../index.js";

export interface InstagramResolverResponse {
    /** `true` when resolved. */
    success?: boolean | undefined;
    /** The account that posted it: `username`, `avatar`. */
    author?: Record<string, unknown> | undefined;
    /** The account that shared the link: `username`, `full_name`, `id`, `avatar`. */
    sharer?: Record<string, unknown> | undefined;
    /** ID of the shared post. */
    entity_id?: string | undefined;
    _meta?: OsintCat.UsageMeta | undefined;
    /** Accepts any additional properties */
    [key: string]: any;
}
