// This file was auto-generated by Fern from our API Definition.

export interface IpResponse {
    /** Services seen on the address: open ports, banners, hostnames, known vulnerabilities. `{"error": "No information available for that IP."}` when nothing was seen. */
    ipleaks?: Record<string, unknown> | undefined;
    /** Location and network: country, region, city, coordinates, time zone, ASN and organisation. */
    ipinfo?: Record<string, unknown> | undefined;
    /** Accepts any additional properties */
    [key: string]: any;
}
