// This file was auto-generated by Fern from our API Definition.

import type * as OsintCat from "../index.js";

export interface MachineFileResponse {
    success?: boolean | undefined;
    info?: OsintCat.MachineFileInfo | undefined;
    /** Accepts any additional properties */
    [key: string]: any;
}
