// This file was auto-generated by Fern from our API Definition.

export interface MachineFileInfo {
    id?: string | undefined;
    machine_id?: string | undefined;
    machine_name?: string | undefined;
    path?: string | undefined;
    filename?: string | undefined;
    size?: number | undefined;
    /** The file content as text. */
    content?: string | undefined;
    is_password_file?: boolean | undefined;
    is_token_file?: boolean | undefined;
    /** Accepts any additional properties */
    [key: string]: any;
}
