// This file was auto-generated by Fern from our API Definition.

export interface MachineViewerStats {
    /** Machines. */
    total_machines?: number | undefined;
    /** Files. */
    total_files?: number | undefined;
    /** Passwords. */
    total_passwords?: number | undefined;
    /** Distinct passwords. */
    total_unique_passwords?: number | undefined;
    /** Tokens. */
    total_tokens?: number | undefined;
    /** Cookies. */
    total_cookies?: number | undefined;
    /** Payment cards. */
    total_credit_cards?: number | undefined;
    /** Size of all files, in bytes. */
    total_size?: number | undefined;
    /** Accepts any additional properties */
    [key: string]: any;
}
