// This file was auto-generated by Fern from our API Definition.

export interface Machine {
    /** Machine ID (a UUID). */
    id?: string | undefined;
    /** Name of the log the machine came from. */
    name?: string | undefined;
    /** When it was added (ISO 8601). */
    imported_at?: string | undefined;
    /** Country code, if known. */
    country?: string | undefined;
    /** IP address, if known. */
    ip?: string | undefined;
    file_count?: number | undefined;
    /** Size of all files, in bytes. */
    total_size?: number | undefined;
    has_passwords?: boolean | undefined;
    password_count?: number | undefined;
    unique_password_count?: number | undefined;
    has_tokens?: boolean | undefined;
    token_count?: number | undefined;
    has_cookies?: boolean | undefined;
    cookie_count?: number | undefined;
    has_credit_cards?: boolean | undefined;
    credit_card_count?: number | undefined;
    /** Accepts any additional properties */
    [key: string]: any;
}
