// This file was auto-generated by Fern from our API Definition.

import type * as OsintCat from "../index.js";

export interface MachineInfoResponse {
    success?: boolean | undefined;
    machine?: OsintCat.Machine | undefined;
    /** E-mail addresses found on the machine. */
    emails?: string[] | undefined;
    /** Tokens found on the machine. */
    tokens?: string[] | undefined;
    /** Accepts any additional properties */
    [key: string]: any;
}
