// This file was auto-generated by Fern from our API Definition.

export interface MachineFile {
    /** File ID, for the file endpoints. */
    id?: string | undefined;
    /** File name. */
    name?: string | undefined;
    /** Path inside the log. */
    path?: string | undefined;
    /** Size in bytes. */
    size?: number | undefined;
    /** Always `file`. */
    type?: string | undefined;
    is_password_file?: boolean | undefined;
    is_token_file?: boolean | undefined;
    /** Accepts any additional properties */
    [key: string]: any;
}
