// This file was auto-generated by Fern from our API Definition.

import type * as OsintCat from "../index.js";

export interface MachineFilesResponse {
    success?: boolean | undefined;
    /** Every file of the machine, with its path. */
    tree?: OsintCat.MachineFile[] | undefined;
    /** Accepts any additional properties */
    [key: string]: any;
}
