// This file was auto-generated by Fern from our API Definition.

import type * as OsintCat from "../index.js";

export interface MachineSearchResponse {
    success?: boolean | undefined;
    query?: string | undefined;
    total?: number | undefined;
    machines?: OsintCat.Machine[] | undefined;
    /** Accepts any additional properties */
    [key: string]: any;
}
