// This file was auto-generated by Fern from our API Definition.

export interface MinecraftResponse {
    /** The query. */
    query?: string | undefined;
    /** Minecraft UUID, or `null`. */
    uuid?: string | undefined;
    /** Current username, or `null`. */
    username?: string | undefined;
    /** Earlier usernames. */
    "name-history"?: unknown[] | undefined;
    /** Capes on the account. */
    capes?: unknown[] | undefined;
    /** Skins the account has used. */
    skinHistory?: unknown[] | undefined;
    /** Records from Minecraft server leaks; `{"error": ...}` when the leak search was unavailable. */
    results?: unknown | undefined;
    /** Accepts any additional properties */
    [key: string]: any;
}
