// This file was auto-generated by Fern from our API Definition.

export interface MinecraftProfileExtraData {
    /** Current username. */
    Username?: string | undefined;
    /** Minecraft UUID. */
    UUID?: string | undefined;
    /** Earlier usernames. */
    NameHistory?: unknown[] | undefined;
    /** Username shown by the LabyMod profile, if any. */
    LabyUsername?: string | undefined;
    /** Head render of the skin. */
    ProfilePicUrl?: string | undefined;
    /** Accepts any additional properties */
    [key: string]: any;
}
