// This file was auto-generated by Fern from our API Definition.

/**
 * The matching leak records. Their fields depend on the server the leak comes from. Results may come from a cache for up to two days.
 */
export type MinecraftOsintResponse = unknown;
