// This file was auto-generated by Fern from our API Definition.

export interface ModulesModules {
    /** Module id. */
    id?: string | undefined;
    /** Display name. */
    name?: string | undefined;
    /** Category it is listed under. */
    category?: string | undefined;
    /** Whether the module is switched on. */
    enabled?: boolean | undefined;
    /** `public`, `beta`, `staff` or `nobody`. */
    access_level?: string | undefined;
    /** Plans the module is limited to (empty: all plans). */
    allowed_plans?: unknown[] | undefined;
    /** Whether your account can use it right now. */
    accessible?: boolean | undefined;
    /** Shown, but not usable on your plan. */
    locked?: boolean | undefined;
    /** Accepts any additional properties */
    [key: string]: any;
}
