// This file was auto-generated by Fern from our API Definition.

export interface ModulesUser {
    /** Plan id. */
    plan?: string | undefined;
    /** Account role. */
    role?: string | undefined;
    /** Whether the account has beta access. */
    beta_access?: boolean | undefined;
    /** Accepts any additional properties */
    [key: string]: any;
}
