// This file was auto-generated by Fern from our API Definition.

import type * as OsintCat from "../index.js";

export interface ModulesResponse {
    /** One entry per module. */
    modules?: OsintCat.ModulesModules[] | undefined;
    user?: OsintCat.ModulesUser | undefined;
    /** Accepts any additional properties */
    [key: string]: any;
}
