// This file was auto-generated by Fern from our API Definition.

import type * as OsintCat from "../index.js";

export interface PhoneOsintResponse {
    /** Always `phone`. */
    module?: string | undefined;
    /** The number in E.164 format. */
    query?: string | undefined;
    /** Whether anything was found. */
    found?: boolean | undefined;
    risk?: OsintCat.PhoneOsintRisk | undefined;
    /** The main facts as `{label, value}` pairs. */
    summary?: unknown[] | undefined;
    /** Detailed findings, grouped (carrier, location, linked accounts ...). */
    sections?: unknown[] | undefined;
    /** The full answer the summary is built from. */
    raw?: Record<string, unknown> | undefined;
    _meta?: OsintCat.UsageMeta | undefined;
    /** Accepts any additional properties */
    [key: string]: any;
}
