// This file was auto-generated by Fern from our API Definition.

export interface PhoneOsintRisk {
    /** Score from 0 to 100, or `null`. */
    score?: number | undefined;
    /** `low`, `medium`, `high` or `unknown`. */
    level?: string | undefined;
    /** Accepts any additional properties */
    [key: string]: any;
}
