// This file was auto-generated by Fern from our API Definition.

export interface RedditExtraData {
    /** Username. */
    Username?: string | undefined;
    /** Display name. */
    DisplayName?: string | undefined;
    /** Comment karma. */
    CommentKarma?: number | undefined;
    /** Post karma. */
    LinkKarma?: number | undefined;
    /** Total karma. */
    TotalKarma?: number | undefined;
    /** Account creation (Unix time). */
    CreatedAt?: number | undefined;
    /** Verified e-mail. */
    IsVerified?: boolean | undefined;
    /** Moderates a community. */
    IsMod?: boolean | undefined;
    /** Present and `true` for suspended accounts. */
    IsSuspended?: boolean | undefined;
    /** Profile link. */
    ProfileUrl?: string | undefined;
    /** Accepts any additional properties */
    [key: string]: any;
}
