// This file was auto-generated by Fern from our API Definition.

export interface SteamExtraData {
    /** Steam username. */
    Username?: string | undefined;
    /** Profile name. */
    DisplayName?: string | undefined;
    /** Real name, if public. */
    RealName?: string | undefined;
    /** Profile link. */
    ProfileUrl?: string | undefined;
    /** Avatar. */
    AvatarUrl?: string | undefined;
    /** 1 when the profile is set up. */
    ProfileState?: number | undefined;
    /** 3 = public, 1 = private. */
    Visibility?: number | undefined;
    /** Account creation (Unix time). */
    TimeCreated?: number | undefined;
    /** Last sign-off (Unix time). */
    LastLogoff?: number | undefined;
    /** Country, if public. */
    CountryCode?: string | undefined;
    /** Accepts any additional properties */
    [key: string]: any;
}
