// This file was auto-generated by Fern from our API Definition.

export interface TiktokResolverResponse {
    /** `true` when resolved. */
    success?: boolean | undefined;
    /** The account that shared the link: `username`, `nickname`, `avatar`, `region`, `language`, `account_created`, `follower_count`, `following_count`, `heart_count`, `video_count`, `bio`, `verified`, `private`. `resolved_via` is `sec_uid` for the sharer, or `video_author` when only the video's author could be identified. */
    sharer?: Record<string, unknown> | undefined;
    /** The share: `shared_from`, `share_time`, `device`, `language`, `region`, `account_created`. */
    share_info?: Record<string, unknown> | undefined;
    /** The video: `full_url`, `video_id`, `video_created`, `type`, `author_username`. */
    video?: Record<string, unknown> | undefined;
    /** Accepts any additional properties */
    [key: string]: any;
}
