// This file was auto-generated by Fern from our API Definition.

export interface TwitterProfile {
    /** Account ID. */
    id?: string | undefined;
    /** Handle. */
    username?: string | undefined;
    /** Display name. */
    name?: string | undefined;
    /** Account creation. */
    created_at?: string | undefined;
    /** Followers. */
    followers?: number | undefined;
    /** Following. */
    following?: number | undefined;
    /** Posts. */
    tweets_count?: number | undefined;
    /** Bio. */
    description?: string | undefined;
    /** Profile picture. */
    profile_image?: string | undefined;
    /** Banner. */
    banner_image?: string | undefined;
    /** Verified. */
    verified?: boolean | undefined;
    /** Accepts any additional properties */
    [key: string]: any;
}
