// This file was auto-generated by Fern from our API Definition.

import type * as OsintCat from "../index.js";

export interface TwitterResponse {
    /** `success`. */
    status?: string | undefined;
    profile?: OsintCat.TwitterProfile | undefined;
    /** How many recent posts the summary is based on. */
    recent_tweets_scraped?: number | undefined;
    /** The automated summary (interests, language, likely region, tone, activity pattern, authenticity estimate). Empty when no summary could be made. */
    ai_analysis?: Record<string, unknown> | undefined;
    /** Accepts any additional properties */
    [key: string]: any;
}
