// This file was auto-generated by Fern from our API Definition.

export interface TwitchExtraData {
    /** Login name. */
    Username?: string | undefined;
    /** Display name. */
    DisplayName?: string | undefined;
    /** Twitch user ID. */
    UserID?: string | undefined;
    /** Bio. */
    Description?: string | undefined;
    /** Profile picture. */
    ProfilePicUrl?: string | undefined;
    /** Followers. */
    Followers?: number | undefined;
    /** Account creation. */
    CreatedAt?: string | undefined;
    /** `partner`, `affiliate` or empty. */
    BroadcasterType?: string | undefined;
    /** Whether the account is suspended (`BanReason` then says why). */
    Banned?: boolean | undefined;
    /** Twitch partner. */
    IsPartner?: boolean | undefined;
    /** Twitch affiliate. */
    IsAffiliate?: boolean | undefined;
    /** Channel link. */
    ProfileUrl?: string | undefined;
    /** Accepts any additional properties */
    [key: string]: any;
}
