// This file was auto-generated by Fern from our API Definition.

/**
 * Your usage after this request.
 */
export interface UsageMeta {
    /** Plan id. */
    plan?: string | undefined;
    /** Lookups left today, `unlimited` on Max, or `charging` when the allowance is used up and the lookup was charged to your balance. */
    lookups_left?: UsageMeta.LookupsLeft | undefined;
    /** Accepts any additional properties */
    [key: string]: any;
}

export namespace UsageMeta {
    /**
     * Lookups left today, `unlimited` on Max, or `charging` when the allowance is used up and the lookup was charged to your balance.
     */
    export type LookupsLeft = number | string;
}
