// This file was auto-generated by Fern from our API Definition.

export interface UserAccountInfo {
    /** Username. */
    username?: string | undefined;
    /** E-mail address of the account. */
    email?: string | undefined;
    /** Current plan, e.g. `Researcher`, `Investigator`, `Max`. */
    plan?: string | undefined;
    /** When the plan ends (ISO 8601), `Lifetime`, or `N/A`. */
    plan_expires?: string | undefined;
    /** Accepts any additional properties */
    [key: string]: any;
}
