// This file was auto-generated by Fern from our API Definition.

export interface UserUsage {
    /** Lookups per day on this plan (Max: unlimited, shown as a very large number). */
    request_limit_daily?: number | undefined;
    /** Lookups left today. Resets at 00:00 UTC. */
    requests_remaining_today?: number | undefined;
    /** Whether the plan includes API access. */
    api_access?: boolean | undefined;
    /** Accepts any additional properties */
    [key: string]: any;
}
