// This file was auto-generated by Fern from our API Definition.

import type * as OsintCat from "../index.js";

export interface UserResponse {
    account_info?: OsintCat.UserAccountInfo | undefined;
    usage?: OsintCat.UserUsage | undefined;
    /** Accepts any additional properties */
    [key: string]: any;
}
