// This file was auto-generated by Fern from our API Definition.

/**
 * The decoder's answer for the chosen `type`, typically `{"Count": n, "Message": "...", "Results": [...]}`. Decoded VINs are cached for an hour.
 */
export interface VinResponse {
    Count?: number | undefined;
    Message?: string | undefined;
    Results?: Record<string, unknown>[] | undefined;
    /** Accepts any additional properties */
    [key: string]: any;
}
