// This file was auto-generated by Fern from our API Definition.

/**
 * The answer depends on `type`: `decode` and `wmi` return one object with the decoded fields (empty strings for fields the VIN does not carry); `batch` and the catalogue types return a list. Decoded VINs are cached for an hour.
 */
export type VinResponse = unknown;
