// This file was auto-generated by Fern from our API Definition.

export interface XboxExtraData {
    /** Gamertag. */
    Gamertag?: string | undefined;
    /** Xbox user ID. */
    XUID?: string | undefined;
    /** Profile link. */
    ProfileUrl?: string | undefined;
    /** Gamer picture. */
    AvatarUrl?: string | undefined;
    /** Gamerscore. */
    GamerScore?: string | undefined;
    /** Account tier. */
    AccountTier?: string | undefined;
    /** Bio. */
    Bio?: string | undefined;
    /** Location, if set. */
    Location?: string | undefined;
    /** Years of membership. */
    Tenure?: string | undefined;
    /** Verified account. */
    IsVerified?: boolean | undefined;
    /** Accepts any additional properties */
    [key: string]: any;
}
