// This file was auto-generated by Fern from our API Definition.

export const QueryVinRequestType = {
    Decode: "decode",
    Batch: "batch",
    Wmi: "wmi",
    Makes: "makes",
    Manufacturers: "manufacturers",
    Variables: "variables",
    Canadian: "canadian",
} as const;
export type QueryVinRequestType = (typeof QueryVinRequestType)[keyof typeof QueryVinRequestType];
