// This file was auto-generated by Fern from our API Definition.

export const QueryVinRequestUnits = {
    Metric: "Metric",
    Us: "US",
} as const;
export type QueryVinRequestUnits = (typeof QueryVinRequestUnits)[keyof typeof QueryVinRequestUnits];
