// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         query: "Juan Perez"
 *     }
 */
export interface PersonChileRequest {
    /** A full or partial name. */
    query: string;
}
