// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         query: "ABCD12"
 *     }
 */
export interface VehicleChileRequest {
    /** The licence plate. */
    query: string;
}
