// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         query: "8.8.8.8"
 *     }
 */
export interface LookupIpRequest {
    /** An IPv4 or IPv6 address. */
    query: string;
}
