// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         username: "unidan"
 *     }
 */
export interface ProfileRedditRequest {
    /** The Reddit username. */
    username: string;
}
