// This file was auto-generated by Fern from our API Definition.

import type * as OsintCat from "../../../../index.js";

/**
 * @example
 *     {
 *         query: "1HGCM82633A004352"
 *     }
 */
export interface QueryVinRequest {
    /** `decode` (default), `batch`, `wmi`, `makes`, `manufacturers`, `variables` or `canadian`. */
    type?: OsintCat.QueryVinRequestType;
    /** The VIN (`decode`), VINs separated by new lines, up to 50 (`batch`), a WMI (`wmi`), or the make / manufacturer / variable name the chosen `search_type` needs. Not needed for `makes`+`all`, `manufacturers`+`all`/`parts`, `variables`+`list` and `canadian`. */
    query?: string;
    /** `decode`: model year, improves accuracy. */
    model_year?: number;
    /** `decode`: `true` for the extended field set. */
    extended?: boolean;
    /** `makes`: `all`, `manufacturer`, `vehicletype`, `models`, `vehicletypes`. `manufacturers`: `all`, `details`, `wmis`, `parts`. `variables`: `list`, `values`. */
    search_type?: string;
    /** `makes` with `manufacturer`/`models`, and `canadian`: model year. */
    year?: number;
    /** `makes`+`models` and `manufacturers`+`wmis`: vehicle type filter. */
    vehicle_type?: string;
    /** `manufacturers`+`all`: manufacturer type filter. */
    mfr_type?: string;
    /** `manufacturers`+`all`/`parts`: page number. */
    page?: number;
    /** `manufacturers`+`parts`: CFR part, default `565`. */
    parts_type?: string;
    /** `manufacturers`+`parts`: start date (required there). */
    from_date?: string;
    /** `manufacturers`+`parts`: end date (required there). */
    to_date?: string;
    /** `canadian`: make. */
    make?: string;
    /** `canadian`: model. */
    model?: string;
    /** `canadian`: `Metric` (default) or `US`. */
    units?: OsintCat.QueryVinRequestUnits;
}
