// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         link: "https://www.instagram.com/reel/Cexample/?igsh=MWexample"
 *     }
 */
export interface ResolveShareLinkInstagramRequest {
    /** An Instagram post or reel share link (with its `igsh` parameter). `url` or `query` are accepted as well. */
    link: string;
}
