// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         query: "user@example.com",
 *         purpose: "fraud prevention"
 *     }
 */
export interface LookupEmailRequest {
    /** The e-mail address (`email` is accepted as well). */
    query: string;
    /** Why you run the lookup, e.g. `fraud prevention`. Required unless sent as a header (below). */
    purpose: string;
}
