// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         username: "octocat"
 *     }
 */
export interface ProfileGithubRequest {
    /** The GitHub username. */
    username: string;
}
