// This file was auto-generated by Fern from our API Definition.

import * as OsintCat from "../../src/api/index";
import { OsintCatClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("AccountClient", () => {
    test("get (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new OsintCatClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {
            account_info: {
                username: "analyst",
                email: "analyst@example.com",
                plan: "Investigator",
                plan_expires: "2026-11-05T09:12:44",
            },
            usage: { request_limit_daily: 750, requests_remaining_today: 742, api_access: true },
        };

        server.mockEndpoint().get("/api/user").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.account.get();
        expect(response).toEqual(rawResponseBody);
    });

    test("get (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new OsintCatClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server.mockEndpoint().get("/api/user").respondWith().statusCode(401).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.account.get();
        }).rejects.toThrow(OsintCat.UnauthorizedError);
    });

    test("get (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new OsintCatClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server.mockEndpoint().get("/api/user").respondWith().statusCode(403).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.account.get();
        }).rejects.toThrow(OsintCat.ForbiddenError);
    });

    test("get (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new OsintCatClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server.mockEndpoint().get("/api/user").respondWith().statusCode(429).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.account.get();
        }).rejects.toThrow(OsintCat.TooManyRequestsError);
    });

    test("modules (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new OsintCatClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {
            modules: [
                {
                    id: "id",
                    name: "name",
                    category: "category",
                    enabled: true,
                    access_level: "access_level",
                    allowed_plans: [{ key: "value" }, { key: "value" }],
                    accessible: true,
                    locked: true,
                },
                {
                    id: "id",
                    name: "name",
                    category: "category",
                    enabled: true,
                    access_level: "access_level",
                    allowed_plans: [{ key: "value" }, { key: "value" }],
                    accessible: true,
                    locked: true,
                },
            ],
            user: { plan: "plan", role: "role", beta_access: true },
        };

        server.mockEndpoint().get("/api/modules").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.account.modules();
        expect(response).toEqual(rawResponseBody);
    });

    test("modules (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new OsintCatClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server.mockEndpoint().get("/api/modules").respondWith().statusCode(401).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.account.modules();
        }).rejects.toThrow(OsintCat.UnauthorizedError);
    });

    test("modules (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new OsintCatClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server.mockEndpoint().get("/api/modules").respondWith().statusCode(403).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.account.modules();
        }).rejects.toThrow(OsintCat.ForbiddenError);
    });

    test("modules (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new OsintCatClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server.mockEndpoint().get("/api/modules").respondWith().statusCode(429).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.account.modules();
        }).rejects.toThrow(OsintCat.TooManyRequestsError);
    });
});
