// This file was auto-generated by Fern from our API Definition.

import * as OsintCat from "../../src/api/index";
import { OsintCatClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("ChessClient", () => {
    test("lookup (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new OsintCatClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {
            success: true,
            found: true,
            query: "hikaru",
            resolved_username: "hikaru",
            live_profile: { username: "hikaru", country: "US", joined: 1389043258 },
            live_stats: { rapid: 2850, blitz: 3300, bullet: 3200, fide: 2800 },
            live_clubs: [{ key: "value" }],
            leak_records: [{ key: "value" }],
            leak_count: 0,
        };

        server.mockEndpoint().get("/api/chess-osint").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.chess.lookup({
            query: "hikaru",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("lookup (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new OsintCatClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server.mockEndpoint().get("/api/chess-osint").respondWith().statusCode(401).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.chess.lookup({
                query: "query",
            });
        }).rejects.toThrow(OsintCat.UnauthorizedError);
    });

    test("lookup (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new OsintCatClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server.mockEndpoint().get("/api/chess-osint").respondWith().statusCode(403).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.chess.lookup({
                query: "query",
            });
        }).rejects.toThrow(OsintCat.ForbiddenError);
    });

    test("lookup (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new OsintCatClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server.mockEndpoint().get("/api/chess-osint").respondWith().statusCode(429).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.chess.lookup({
                query: "query",
            });
        }).rejects.toThrow(OsintCat.TooManyRequestsError);
    });
});
