// This file was auto-generated by Fern from our API Definition.

import * as OsintCat from "../../src/api/index";
import { OsintCatClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("DnsClient", () => {
    test("resolve (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new OsintCatClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { "example.com": "93.184.215.14", "osintcat.net": "104.21.32.1" };

        server.mockEndpoint().get("/api/dns-resolver").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.dns.resolve({
            query: "example.com,osintcat.net",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("resolve (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new OsintCatClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server.mockEndpoint().get("/api/dns-resolver").respondWith().statusCode(401).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.dns.resolve({
                query: "query",
            });
        }).rejects.toThrow(OsintCat.UnauthorizedError);
    });

    test("resolve (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new OsintCatClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server.mockEndpoint().get("/api/dns-resolver").respondWith().statusCode(403).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.dns.resolve({
                query: "query",
            });
        }).rejects.toThrow(OsintCat.ForbiddenError);
    });

    test("resolve (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new OsintCatClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server.mockEndpoint().get("/api/dns-resolver").respondWith().statusCode(424).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.dns.resolve({
                query: "query",
            });
        }).rejects.toThrow(OsintCat.FailedDependencyError);
    });

    test("resolve (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new OsintCatClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server.mockEndpoint().get("/api/dns-resolver").respondWith().statusCode(429).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.dns.resolve({
                query: "query",
            });
        }).rejects.toThrow(OsintCat.TooManyRequestsError);
    });
});
