// This file was auto-generated by Fern from our API Definition.

import * as OsintCat from "../../src/api/index";
import { OsintCatClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("EmailClient", () => {
    test("lookup (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new OsintCatClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {
            results: {
                register: [{ site: "example-shop.com", exists: true }],
                breach: [{ name: "Example 2021", date: "2021-04-02" }],
                api: [{ key: "value" }],
            },
            _meta: { plan: "investigator", lookups_left: 739 },
        };

        server.mockEndpoint().get("/api/email-osint").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.email.lookup({
            query: "user@example.com",
            purpose: "fraud prevention",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("lookup (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new OsintCatClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server.mockEndpoint().get("/api/email-osint").respondWith().statusCode(400).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.email.lookup({
                query: "query",
                purpose: "purpose",
            });
        }).rejects.toThrow(OsintCat.BadRequestError);
    });

    test("lookup (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new OsintCatClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server.mockEndpoint().get("/api/email-osint").respondWith().statusCode(401).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.email.lookup({
                query: "query",
                purpose: "purpose",
            });
        }).rejects.toThrow(OsintCat.UnauthorizedError);
    });

    test("lookup (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new OsintCatClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server.mockEndpoint().get("/api/email-osint").respondWith().statusCode(402).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.email.lookup({
                query: "query",
                purpose: "purpose",
            });
        }).rejects.toThrow(OsintCat.PaymentRequiredError);
    });

    test("lookup (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new OsintCatClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server.mockEndpoint().get("/api/email-osint").respondWith().statusCode(403).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.email.lookup({
                query: "query",
                purpose: "purpose",
            });
        }).rejects.toThrow(OsintCat.ForbiddenError);
    });

    test("lookup (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new OsintCatClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server.mockEndpoint().get("/api/email-osint").respondWith().statusCode(424).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.email.lookup({
                query: "query",
                purpose: "purpose",
            });
        }).rejects.toThrow(OsintCat.FailedDependencyError);
    });

    test("lookup (7)", async () => {
        const server = mockServerPool.createServer();
        const client = new OsintCatClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server.mockEndpoint().get("/api/email-osint").respondWith().statusCode(429).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.email.lookup({
                query: "query",
                purpose: "purpose",
            });
        }).rejects.toThrow(OsintCat.TooManyRequestsError);
    });
});
