// This file was auto-generated by Fern from our API Definition.

import * as OsintCat from "../../src/api/index";
import { OsintCatClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("GithubClient", () => {
    test("profile (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new OsintCatClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {
            taken: true,
            error: "error",
            ExtraData: {
                Username: "octocat",
                Name: "The Octocat",
                Bio: "Bio",
                Location: "San Francisco",
                Company: "Company",
                Blog: "Blog",
                Email: "Email",
                Twitter: "Twitter",
                Followers: 21000,
                Following: 1.1,
                PublicRepos: 8,
                CreatedAt: "2011-01-25T18:44:36Z",
                ProfileUrl: "https://github.com/octocat",
                Repositories: [{ key: "value" }],
            },
        };

        server.mockEndpoint().get("/api/github-lookup").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.github.profile({
            username: "octocat",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("profile (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new OsintCatClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server.mockEndpoint().get("/api/github-lookup").respondWith().statusCode(400).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.github.profile({
                username: "username",
            });
        }).rejects.toThrow(OsintCat.BadRequestError);
    });

    test("profile (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new OsintCatClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server.mockEndpoint().get("/api/github-lookup").respondWith().statusCode(401).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.github.profile({
                username: "username",
            });
        }).rejects.toThrow(OsintCat.UnauthorizedError);
    });

    test("profile (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new OsintCatClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server.mockEndpoint().get("/api/github-lookup").respondWith().statusCode(403).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.github.profile({
                username: "username",
            });
        }).rejects.toThrow(OsintCat.ForbiddenError);
    });

    test("profile (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new OsintCatClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server.mockEndpoint().get("/api/github-lookup").respondWith().statusCode(429).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.github.profile({
                username: "username",
            });
        }).rejects.toThrow(OsintCat.TooManyRequestsError);
    });
});
