// This file was auto-generated by Fern from our API Definition.

import * as OsintCat from "../../src/api/index";
import { OsintCatClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("InstagramClient", () => {
    test("resolveShareLink (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new OsintCatClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {
            success: true,
            author: { key: "value" },
            sharer: { key: "value" },
            entity_id: "entity_id",
            _meta: { plan: "plan", lookups_left: 1.1 },
        };

        server
            .mockEndpoint()
            .get("/api/instagram-resolver")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.instagram.resolveShareLink({
            link: "https://www.instagram.com/reel/Cexample/?igsh=MWexample",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("resolveShareLink (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new OsintCatClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .get("/api/instagram-resolver")
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.instagram.resolveShareLink({
                link: "link",
            });
        }).rejects.toThrow(OsintCat.BadRequestError);
    });

    test("resolveShareLink (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new OsintCatClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .get("/api/instagram-resolver")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.instagram.resolveShareLink({
                link: "link",
            });
        }).rejects.toThrow(OsintCat.UnauthorizedError);
    });

    test("resolveShareLink (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new OsintCatClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .get("/api/instagram-resolver")
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.instagram.resolveShareLink({
                link: "link",
            });
        }).rejects.toThrow(OsintCat.ForbiddenError);
    });

    test("resolveShareLink (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new OsintCatClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .get("/api/instagram-resolver")
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.instagram.resolveShareLink({
                link: "link",
            });
        }).rejects.toThrow(OsintCat.UnprocessableEntityError);
    });

    test("resolveShareLink (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new OsintCatClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .get("/api/instagram-resolver")
            .respondWith()
            .statusCode(424)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.instagram.resolveShareLink({
                link: "link",
            });
        }).rejects.toThrow(OsintCat.FailedDependencyError);
    });

    test("resolveShareLink (7)", async () => {
        const server = mockServerPool.createServer();
        const client = new OsintCatClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .get("/api/instagram-resolver")
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.instagram.resolveShareLink({
                link: "link",
            });
        }).rejects.toThrow(OsintCat.TooManyRequestsError);
    });
});
