// This file was auto-generated by Fern from our API Definition.

import * as OsintCat from "../../src/api/index";
import { OsintCatClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("IpClient", () => {
    test("lookup (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new OsintCatClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {
            ipleaks: { ip_str: "8.8.8.8", ports: [53, 443], hostnames: ["dns.google"], org: "Google LLC" },
            ipinfo: {
                ipAddress: "8.8.8.8",
                countryName: "United States of America",
                countryCode: "US",
                cityName: "Mountain View",
                asn: "15169",
                asnOrganization: "Google LLC",
            },
        };

        server.mockEndpoint().get("/api/ip").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.ip.lookup({
            query: "8.8.8.8",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("lookup (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new OsintCatClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server.mockEndpoint().get("/api/ip").respondWith().statusCode(401).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.ip.lookup({
                query: "query",
            });
        }).rejects.toThrow(OsintCat.UnauthorizedError);
    });

    test("lookup (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new OsintCatClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server.mockEndpoint().get("/api/ip").respondWith().statusCode(403).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.ip.lookup({
                query: "query",
            });
        }).rejects.toThrow(OsintCat.ForbiddenError);
    });

    test("lookup (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new OsintCatClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server.mockEndpoint().get("/api/ip").respondWith().statusCode(424).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.ip.lookup({
                query: "query",
            });
        }).rejects.toThrow(OsintCat.FailedDependencyError);
    });

    test("lookup (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new OsintCatClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server.mockEndpoint().get("/api/ip").respondWith().statusCode(429).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.ip.lookup({
                query: "query",
            });
        }).rejects.toThrow(OsintCat.TooManyRequestsError);
    });
});
