// This file was auto-generated by Fern from our API Definition.

import * as OsintCat from "../../src/api/index";
import { OsintCatClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("MachineViewerClient", () => {
    test("stats (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new OsintCatClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {
            total_machines: 1,
            total_files: 1,
            total_passwords: 1,
            total_unique_passwords: 1,
            total_tokens: 1,
            total_cookies: 1,
            total_credit_cards: 1,
            total_size: 1,
        };

        server
            .mockEndpoint()
            .get("/api/machine_viewer/stats")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.machineViewer.stats();
        expect(response).toEqual(rawResponseBody);
    });

    test("stats (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new OsintCatClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .get("/api/machine_viewer/stats")
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.machineViewer.stats();
        }).rejects.toThrow(OsintCat.BadRequestError);
    });

    test("stats (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new OsintCatClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .get("/api/machine_viewer/stats")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.machineViewer.stats();
        }).rejects.toThrow(OsintCat.UnauthorizedError);
    });

    test("stats (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new OsintCatClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .get("/api/machine_viewer/stats")
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.machineViewer.stats();
        }).rejects.toThrow(OsintCat.ForbiddenError);
    });

    test("stats (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new OsintCatClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .get("/api/machine_viewer/stats")
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.machineViewer.stats();
        }).rejects.toThrow(OsintCat.TooManyRequestsError);
    });

    test("search (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new OsintCatClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {
            success: true,
            query: "query",
            total: 1,
            machines: [
                {
                    id: "id",
                    name: "name",
                    imported_at: "imported_at",
                    country: "country",
                    ip: "ip",
                    file_count: 1,
                    total_size: 1,
                    has_passwords: true,
                    password_count: 1,
                    unique_password_count: 1,
                    has_tokens: true,
                    token_count: 1,
                    has_cookies: true,
                    cookie_count: 1,
                    has_credit_cards: true,
                    credit_card_count: 1,
                },
            ],
        };

        server
            .mockEndpoint()
            .get("/api/machine_viewer/search")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.machineViewer.search({
            query: "DESKTOP",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("search (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new OsintCatClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .get("/api/machine_viewer/search")
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.machineViewer.search({
                query: "query",
            });
        }).rejects.toThrow(OsintCat.BadRequestError);
    });

    test("search (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new OsintCatClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .get("/api/machine_viewer/search")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.machineViewer.search({
                query: "query",
            });
        }).rejects.toThrow(OsintCat.UnauthorizedError);
    });

    test("search (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new OsintCatClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .get("/api/machine_viewer/search")
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.machineViewer.search({
                query: "query",
            });
        }).rejects.toThrow(OsintCat.ForbiddenError);
    });

    test("search (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new OsintCatClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .get("/api/machine_viewer/search")
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.machineViewer.search({
                query: "query",
            });
        }).rejects.toThrow(OsintCat.TooManyRequestsError);
    });

    test("machine (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new OsintCatClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {
            success: true,
            machine: {
                id: "id",
                name: "name",
                imported_at: "imported_at",
                country: "country",
                ip: "ip",
                file_count: 1,
                total_size: 1,
                has_passwords: true,
                password_count: 1,
                unique_password_count: 1,
                has_tokens: true,
                token_count: 1,
                has_cookies: true,
                cookie_count: 1,
                has_credit_cards: true,
                credit_card_count: 1,
            },
            emails: ["emails"],
            tokens: ["tokens"],
        };

        server
            .mockEndpoint()
            .get("/api/machine_viewer/machines/742e1f66-f449-4a6c-80d5-8f5eb8e9c2b5/info")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.machineViewer.machine({
            machine_id: "742e1f66-f449-4a6c-80d5-8f5eb8e9c2b5",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("machine (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new OsintCatClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .get("/api/machine_viewer/machines/machine_id/info")
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.machineViewer.machine({
                machine_id: "machine_id",
            });
        }).rejects.toThrow(OsintCat.BadRequestError);
    });

    test("machine (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new OsintCatClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .get("/api/machine_viewer/machines/machine_id/info")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.machineViewer.machine({
                machine_id: "machine_id",
            });
        }).rejects.toThrow(OsintCat.UnauthorizedError);
    });

    test("machine (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new OsintCatClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .get("/api/machine_viewer/machines/machine_id/info")
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.machineViewer.machine({
                machine_id: "machine_id",
            });
        }).rejects.toThrow(OsintCat.ForbiddenError);
    });

    test("machine (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new OsintCatClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .get("/api/machine_viewer/machines/machine_id/info")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.machineViewer.machine({
                machine_id: "machine_id",
            });
        }).rejects.toThrow(OsintCat.NotFoundError);
    });

    test("machine (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new OsintCatClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .get("/api/machine_viewer/machines/machine_id/info")
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.machineViewer.machine({
                machine_id: "machine_id",
            });
        }).rejects.toThrow(OsintCat.TooManyRequestsError);
    });

    test("files (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new OsintCatClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {
            success: true,
            tree: [
                {
                    id: "id",
                    name: "name",
                    path: "path",
                    size: 1,
                    type: "type",
                    is_password_file: true,
                    is_token_file: true,
                },
            ],
        };

        server
            .mockEndpoint()
            .get("/api/machine_viewer/machines/742e1f66-f449-4a6c-80d5-8f5eb8e9c2b5/files/treeview")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.machineViewer.files({
            machine_id: "742e1f66-f449-4a6c-80d5-8f5eb8e9c2b5",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("files (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new OsintCatClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .get("/api/machine_viewer/machines/machine_id/files/treeview")
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.machineViewer.files({
                machine_id: "machine_id",
            });
        }).rejects.toThrow(OsintCat.BadRequestError);
    });

    test("files (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new OsintCatClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .get("/api/machine_viewer/machines/machine_id/files/treeview")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.machineViewer.files({
                machine_id: "machine_id",
            });
        }).rejects.toThrow(OsintCat.UnauthorizedError);
    });

    test("files (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new OsintCatClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .get("/api/machine_viewer/machines/machine_id/files/treeview")
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.machineViewer.files({
                machine_id: "machine_id",
            });
        }).rejects.toThrow(OsintCat.ForbiddenError);
    });

    test("files (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new OsintCatClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .get("/api/machine_viewer/machines/machine_id/files/treeview")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.machineViewer.files({
                machine_id: "machine_id",
            });
        }).rejects.toThrow(OsintCat.NotFoundError);
    });

    test("files (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new OsintCatClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .get("/api/machine_viewer/machines/machine_id/files/treeview")
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.machineViewer.files({
                machine_id: "machine_id",
            });
        }).rejects.toThrow(OsintCat.TooManyRequestsError);
    });

    test("file (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new OsintCatClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {
            success: true,
            info: {
                id: "id",
                machine_id: "machine_id",
                machine_name: "machine_name",
                path: "path",
                filename: "filename",
                size: 1,
                content: "content",
                is_password_file: true,
                is_token_file: true,
            },
        };

        server
            .mockEndpoint()
            .get("/api/machine_viewer/files/aB3dE5fG7hI9jK1lM3nO/info")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.machineViewer.file({
            file_id: "aB3dE5fG7hI9jK1lM3nO",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("file (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new OsintCatClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .get("/api/machine_viewer/files/file_id/info")
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.machineViewer.file({
                file_id: "file_id",
            });
        }).rejects.toThrow(OsintCat.BadRequestError);
    });

    test("file (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new OsintCatClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .get("/api/machine_viewer/files/file_id/info")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.machineViewer.file({
                file_id: "file_id",
            });
        }).rejects.toThrow(OsintCat.UnauthorizedError);
    });

    test("file (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new OsintCatClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .get("/api/machine_viewer/files/file_id/info")
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.machineViewer.file({
                file_id: "file_id",
            });
        }).rejects.toThrow(OsintCat.ForbiddenError);
    });

    test("file (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new OsintCatClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .get("/api/machine_viewer/files/file_id/info")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.machineViewer.file({
                file_id: "file_id",
            });
        }).rejects.toThrow(OsintCat.NotFoundError);
    });

    test("file (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new OsintCatClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .get("/api/machine_viewer/files/file_id/info")
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.machineViewer.file({
                file_id: "file_id",
            });
        }).rejects.toThrow(OsintCat.TooManyRequestsError);
    });
});
