// This file was auto-generated by Fern from our API Definition.

import * as OsintCat from "../../src/api/index";
import { OsintCatClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("MinecraftClient", () => {
    test("player (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new OsintCatClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {
            query: "notch",
            uuid: "069a79f444e94726a5befca90e38aaf5",
            username: "Notch",
            "name-history": [{ name: "Notch" }],
            capes: [{ key: "value" }],
            skinHistory: [{ key: "value" }],
            results: { key: "value" },
        };

        server.mockEndpoint().get("/api/minecraft").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.minecraft.player({
            query: "Notch",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("player (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new OsintCatClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server.mockEndpoint().get("/api/minecraft").respondWith().statusCode(401).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.minecraft.player({
                query: "query",
            });
        }).rejects.toThrow(OsintCat.UnauthorizedError);
    });

    test("player (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new OsintCatClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server.mockEndpoint().get("/api/minecraft").respondWith().statusCode(403).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.minecraft.player({
                query: "query",
            });
        }).rejects.toThrow(OsintCat.ForbiddenError);
    });

    test("player (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new OsintCatClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server.mockEndpoint().get("/api/minecraft").respondWith().statusCode(424).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.minecraft.player({
                query: "query",
            });
        }).rejects.toThrow(OsintCat.FailedDependencyError);
    });

    test("player (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new OsintCatClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server.mockEndpoint().get("/api/minecraft").respondWith().statusCode(429).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.minecraft.player({
                query: "query",
            });
        }).rejects.toThrow(OsintCat.TooManyRequestsError);
    });

    test("leaks (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new OsintCatClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/api/minecraft-lookup")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.minecraft.leaks({
            query: "Notch",
            type: "username",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("leaks (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new OsintCatClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .get("/api/minecraft-lookup")
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.minecraft.leaks({
                query: "query",
                type: "username",
            });
        }).rejects.toThrow(OsintCat.BadRequestError);
    });

    test("leaks (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new OsintCatClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .get("/api/minecraft-lookup")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.minecraft.leaks({
                query: "query",
                type: "username",
            });
        }).rejects.toThrow(OsintCat.UnauthorizedError);
    });

    test("leaks (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new OsintCatClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .get("/api/minecraft-lookup")
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.minecraft.leaks({
                query: "query",
                type: "username",
            });
        }).rejects.toThrow(OsintCat.ForbiddenError);
    });

    test("leaks (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new OsintCatClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .get("/api/minecraft-lookup")
            .respondWith()
            .statusCode(424)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.minecraft.leaks({
                query: "query",
                type: "username",
            });
        }).rejects.toThrow(OsintCat.FailedDependencyError);
    });

    test("leaks (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new OsintCatClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .get("/api/minecraft-lookup")
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.minecraft.leaks({
                query: "query",
                type: "username",
            });
        }).rejects.toThrow(OsintCat.TooManyRequestsError);
    });

    test("profile (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new OsintCatClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {
            taken: true,
            error: "error",
            ExtraData: {
                Username: "Notch",
                UUID: "069a79f444e94726a5befca90e38aaf5",
                NameHistory: [{ key: "value" }],
                LabyUsername: "Notch",
                ProfilePicUrl: "https://mc-heads.net/avatar/069a79f444e94726a5befca90e38aaf5",
            },
        };

        server
            .mockEndpoint()
            .get("/api/minecraft-lookup-v2")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.minecraft.profile({
            username: "Notch",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("profile (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new OsintCatClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .get("/api/minecraft-lookup-v2")
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.minecraft.profile({
                username: "username",
            });
        }).rejects.toThrow(OsintCat.BadRequestError);
    });

    test("profile (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new OsintCatClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .get("/api/minecraft-lookup-v2")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.minecraft.profile({
                username: "username",
            });
        }).rejects.toThrow(OsintCat.UnauthorizedError);
    });

    test("profile (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new OsintCatClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .get("/api/minecraft-lookup-v2")
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.minecraft.profile({
                username: "username",
            });
        }).rejects.toThrow(OsintCat.ForbiddenError);
    });

    test("profile (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new OsintCatClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .get("/api/minecraft-lookup-v2")
            .respondWith()
            .statusCode(424)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.minecraft.profile({
                username: "username",
            });
        }).rejects.toThrow(OsintCat.FailedDependencyError);
    });

    test("profile (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new OsintCatClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .get("/api/minecraft-lookup-v2")
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.minecraft.profile({
                username: "username",
            });
        }).rejects.toThrow(OsintCat.TooManyRequestsError);
    });
});
