// This file was auto-generated by Fern from our API Definition.

import * as OsintCat from "../../src/api/index";
import { OsintCatClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("PhoneClient", () => {
    test("lookup (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new OsintCatClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {
            module: "phone",
            query: "+4915112345678",
            found: true,
            risk: { score: 12, level: "low" },
            summary: [
                { label: "Number", value: "+4915112345678" },
                { label: "Valid number", value: "Yes" },
                { label: "Carrier", value: "Telekom Deutschland" },
                { label: "Line type", value: "Mobile" },
            ],
            sections: [{ key: "value" }],
            raw: { key: "value" },
            _meta: { plan: "investigator", lookups_left: 740 },
        };

        server.mockEndpoint().get("/api/phone-osint").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.phone.lookup({
            query: "+4915112345678",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("lookup (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new OsintCatClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server.mockEndpoint().get("/api/phone-osint").respondWith().statusCode(400).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.phone.lookup({
                query: "query",
            });
        }).rejects.toThrow(OsintCat.BadRequestError);
    });

    test("lookup (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new OsintCatClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server.mockEndpoint().get("/api/phone-osint").respondWith().statusCode(401).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.phone.lookup({
                query: "query",
            });
        }).rejects.toThrow(OsintCat.UnauthorizedError);
    });

    test("lookup (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new OsintCatClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server.mockEndpoint().get("/api/phone-osint").respondWith().statusCode(403).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.phone.lookup({
                query: "query",
            });
        }).rejects.toThrow(OsintCat.ForbiddenError);
    });

    test("lookup (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new OsintCatClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server.mockEndpoint().get("/api/phone-osint").respondWith().statusCode(424).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.phone.lookup({
                query: "query",
            });
        }).rejects.toThrow(OsintCat.FailedDependencyError);
    });

    test("lookup (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new OsintCatClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server.mockEndpoint().get("/api/phone-osint").respondWith().statusCode(429).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.phone.lookup({
                query: "query",
            });
        }).rejects.toThrow(OsintCat.TooManyRequestsError);
    });
});
