// This file was auto-generated by Fern from our API Definition.

import * as OsintCat from "../../src/api/index";
import { OsintCatClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("SteamClient", () => {
    test("profile (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new OsintCatClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {
            taken: true,
            error: "error",
            ExtraData: {
                Username: "gaben",
                DisplayName: "Rabscuttle",
                RealName: "RealName",
                ProfileUrl: "https://steamcommunity.com/profiles/76561197960287930",
                AvatarUrl: "AvatarUrl",
                ProfileState: 1.1,
                Visibility: 3,
                TimeCreated: 1063407589,
                LastLogoff: 1.1,
                CountryCode: "US",
            },
        };

        server.mockEndpoint().get("/api/steam-lookup").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.steam.profile({
            username: "gaben",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("profile (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new OsintCatClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server.mockEndpoint().get("/api/steam-lookup").respondWith().statusCode(400).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.steam.profile({
                username: "username",
            });
        }).rejects.toThrow(OsintCat.BadRequestError);
    });

    test("profile (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new OsintCatClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server.mockEndpoint().get("/api/steam-lookup").respondWith().statusCode(401).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.steam.profile({
                username: "username",
            });
        }).rejects.toThrow(OsintCat.UnauthorizedError);
    });

    test("profile (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new OsintCatClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server.mockEndpoint().get("/api/steam-lookup").respondWith().statusCode(403).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.steam.profile({
                username: "username",
            });
        }).rejects.toThrow(OsintCat.ForbiddenError);
    });

    test("profile (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new OsintCatClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server.mockEndpoint().get("/api/steam-lookup").respondWith().statusCode(424).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.steam.profile({
                username: "username",
            });
        }).rejects.toThrow(OsintCat.FailedDependencyError);
    });

    test("profile (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new OsintCatClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server.mockEndpoint().get("/api/steam-lookup").respondWith().statusCode(429).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.steam.profile({
                username: "username",
            });
        }).rejects.toThrow(OsintCat.TooManyRequestsError);
    });
});
