// This file was auto-generated by Fern from our API Definition.

import * as OsintCat from "../../src/api/index";
import { OsintCatClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("TiktokClient", () => {
    test("resolveShareLink (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new OsintCatClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {
            success: true,
            sharer: { key: "value" },
            share_info: { key: "value" },
            video: { key: "value" },
        };

        server
            .mockEndpoint()
            .get("/api/tiktok-resolver")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.tiktok.resolveShareLink({
            link: "https://vm.tiktok.com/ZMexample/",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("resolveShareLink (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new OsintCatClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .get("/api/tiktok-resolver")
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.tiktok.resolveShareLink({
                link: "link",
            });
        }).rejects.toThrow(OsintCat.BadRequestError);
    });

    test("resolveShareLink (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new OsintCatClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .get("/api/tiktok-resolver")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.tiktok.resolveShareLink({
                link: "link",
            });
        }).rejects.toThrow(OsintCat.UnauthorizedError);
    });

    test("resolveShareLink (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new OsintCatClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .get("/api/tiktok-resolver")
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.tiktok.resolveShareLink({
                link: "link",
            });
        }).rejects.toThrow(OsintCat.ForbiddenError);
    });

    test("resolveShareLink (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new OsintCatClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .get("/api/tiktok-resolver")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.tiktok.resolveShareLink({
                link: "link",
            });
        }).rejects.toThrow(OsintCat.NotFoundError);
    });

    test("resolveShareLink (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new OsintCatClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .get("/api/tiktok-resolver")
            .respondWith()
            .statusCode(424)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.tiktok.resolveShareLink({
                link: "link",
            });
        }).rejects.toThrow(OsintCat.FailedDependencyError);
    });

    test("resolveShareLink (7)", async () => {
        const server = mockServerPool.createServer();
        const client = new OsintCatClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .get("/api/tiktok-resolver")
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.tiktok.resolveShareLink({
                link: "link",
            });
        }).rejects.toThrow(OsintCat.TooManyRequestsError);
    });
});
