// This file was auto-generated by Fern from our API Definition.

import * as OsintCat from "../../src/api/index";
import { OsintCatClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("TwitchClient", () => {
    test("profile (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new OsintCatClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {
            taken: true,
            error: "error",
            ExtraData: {
                Username: "xqc",
                DisplayName: "xQc",
                UserID: "71092938",
                Description: "Description",
                ProfilePicUrl: "ProfilePicUrl",
                Followers: 12345678,
                CreatedAt: "2014-09-12T23:50:05Z",
                BroadcasterType: "partner",
                Banned: false,
                IsPartner: true,
                IsAffiliate: true,
                ProfileUrl: "https://twitch.tv/xqc",
            },
        };

        server.mockEndpoint().get("/api/twitch").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.twitch.profile({
            username: "xqc",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("profile (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new OsintCatClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server.mockEndpoint().get("/api/twitch").respondWith().statusCode(400).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.twitch.profile({
                username: "username",
            });
        }).rejects.toThrow(OsintCat.BadRequestError);
    });

    test("profile (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new OsintCatClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server.mockEndpoint().get("/api/twitch").respondWith().statusCode(401).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.twitch.profile({
                username: "username",
            });
        }).rejects.toThrow(OsintCat.UnauthorizedError);
    });

    test("profile (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new OsintCatClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server.mockEndpoint().get("/api/twitch").respondWith().statusCode(403).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.twitch.profile({
                username: "username",
            });
        }).rejects.toThrow(OsintCat.ForbiddenError);
    });

    test("profile (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new OsintCatClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server.mockEndpoint().get("/api/twitch").respondWith().statusCode(429).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.twitch.profile({
                username: "username",
            });
        }).rejects.toThrow(OsintCat.TooManyRequestsError);
    });
});
