// This file was auto-generated by Fern from our API Definition.

import * as OsintCat from "../../src/api/index";
import { OsintCatClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("VinClient", () => {
    test("query (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new OsintCatClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {
            Count: 1,
            Message: "Results returned successfully",
            Results: [{ Make: "HONDA", Model: "Accord", ModelYear: "2003", VIN: "1HGCM82633A004352" }],
        };

        server.mockEndpoint().get("/api/vin").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.vin.query({
            query: "1HGCM82633A004352",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("query (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new OsintCatClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server.mockEndpoint().get("/api/vin").respondWith().statusCode(400).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.vin.query();
        }).rejects.toThrow(OsintCat.BadRequestError);
    });

    test("query (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new OsintCatClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server.mockEndpoint().get("/api/vin").respondWith().statusCode(401).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.vin.query();
        }).rejects.toThrow(OsintCat.UnauthorizedError);
    });

    test("query (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new OsintCatClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server.mockEndpoint().get("/api/vin").respondWith().statusCode(403).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.vin.query();
        }).rejects.toThrow(OsintCat.ForbiddenError);
    });

    test("query (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new OsintCatClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server.mockEndpoint().get("/api/vin").respondWith().statusCode(429).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.vin.query();
        }).rejects.toThrow(OsintCat.TooManyRequestsError);
    });
});
