// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         query: "+4915112345678"
 *     }
 */
export interface LookupPhoneRequest {
    /** The phone number in international format, e.g. `+4915112345678`. Spaces and dashes are allowed. */
    query: string;
}
