// This file was auto-generated by Fern from our API Definition.

import { AccountClient } from "./api/resources/account/client/Client.js";
import { BreachClient } from "./api/resources/breach/client/Client.js";
import { ChessClient } from "./api/resources/chess/client/Client.js";
import { ChileClient } from "./api/resources/chile/client/Client.js";
import { DnsClient } from "./api/resources/dns/client/Client.js";
import { EmailClient } from "./api/resources/email/client/Client.js";
import { GithubClient } from "./api/resources/github/client/Client.js";
import { InstagramClient } from "./api/resources/instagram/client/Client.js";
import { IpClient } from "./api/resources/ip/client/Client.js";
import { MinecraftClient } from "./api/resources/minecraft/client/Client.js";
import { PhoneClient } from "./api/resources/phone/client/Client.js";
import { RedditClient } from "./api/resources/reddit/client/Client.js";
import { SteamClient } from "./api/resources/steam/client/Client.js";
import { TiktokClient } from "./api/resources/tiktok/client/Client.js";
import { TwitchClient } from "./api/resources/twitch/client/Client.js";
import { VinClient } from "./api/resources/vin/client/Client.js";
import { XClient } from "./api/resources/x/client/Client.js";
import { XboxClient } from "./api/resources/xbox/client/Client.js";
import type { BaseClientOptions, BaseRequestOptions } from "./BaseClient.js";
import { type NormalizedClientOptionsWithAuth, normalizeClientOptionsWithAuth } from "./BaseClient.js";
import * as core from "./core/index.js";

export declare namespace OsintCatClient {
    export type Options = BaseClientOptions;

    export interface RequestOptions extends BaseRequestOptions {}
}

export class OsintCatClient {
    protected readonly _options: NormalizedClientOptionsWithAuth<OsintCatClient.Options>;
    protected _account: AccountClient | undefined;
    protected _breach: BreachClient | undefined;
    protected _email: EmailClient | undefined;
    protected _phone: PhoneClient | undefined;
    protected _ip: IpClient | undefined;
    protected _dns: DnsClient | undefined;
    protected _minecraft: MinecraftClient | undefined;
    protected _steam: SteamClient | undefined;
    protected _xbox: XboxClient | undefined;
    protected _twitch: TwitchClient | undefined;
    protected _chess: ChessClient | undefined;
    protected _github: GithubClient | undefined;
    protected _reddit: RedditClient | undefined;
    protected _x: XClient | undefined;
    protected _tiktok: TiktokClient | undefined;
    protected _instagram: InstagramClient | undefined;
    protected _vin: VinClient | undefined;
    protected _chile: ChileClient | undefined;

    constructor(options: OsintCatClient.Options = {}) {
        this._options = normalizeClientOptionsWithAuth(options);
    }

    public get account(): AccountClient {
        return (this._account ??= new AccountClient(this._options));
    }

    public get breach(): BreachClient {
        return (this._breach ??= new BreachClient(this._options));
    }

    public get email(): EmailClient {
        return (this._email ??= new EmailClient(this._options));
    }

    public get phone(): PhoneClient {
        return (this._phone ??= new PhoneClient(this._options));
    }

    public get ip(): IpClient {
        return (this._ip ??= new IpClient(this._options));
    }

    public get dns(): DnsClient {
        return (this._dns ??= new DnsClient(this._options));
    }

    public get minecraft(): MinecraftClient {
        return (this._minecraft ??= new MinecraftClient(this._options));
    }

    public get steam(): SteamClient {
        return (this._steam ??= new SteamClient(this._options));
    }

    public get xbox(): XboxClient {
        return (this._xbox ??= new XboxClient(this._options));
    }

    public get twitch(): TwitchClient {
        return (this._twitch ??= new TwitchClient(this._options));
    }

    public get chess(): ChessClient {
        return (this._chess ??= new ChessClient(this._options));
    }

    public get github(): GithubClient {
        return (this._github ??= new GithubClient(this._options));
    }

    public get reddit(): RedditClient {
        return (this._reddit ??= new RedditClient(this._options));
    }

    public get x(): XClient {
        return (this._x ??= new XClient(this._options));
    }

    public get tiktok(): TiktokClient {
        return (this._tiktok ??= new TiktokClient(this._options));
    }

    public get instagram(): InstagramClient {
        return (this._instagram ??= new InstagramClient(this._options));
    }

    public get vin(): VinClient {
        return (this._vin ??= new VinClient(this._options));
    }

    public get chile(): ChileClient {
        return (this._chile ??= new ChileClient(this._options));
    }

    /**
     * Make a passthrough request using the SDK's configured auth, retry, logging, etc.
     * This is useful for making requests to endpoints not yet supported in the SDK.
     * The input can be a URL string, URL object, or Request object. Relative paths are resolved against the configured base URL.
     *
     * @param {Request | string | URL} input - The URL, path, or Request object.
     * @param {RequestInit} init - Standard fetch RequestInit options.
     * @param {core.PassthroughRequest.RequestOptions} requestOptions - Per-request overrides (timeout, retries, headers, abort signal).
     * @returns {Promise<Response>} A standard Response object.
     */
    public async fetch(
        input: Request | string | URL,
        init?: RequestInit,
        requestOptions?: core.PassthroughRequest.RequestOptions,
    ): Promise<Response> {
        return core.makePassthroughRequest(
            input,
            init,
            {
                baseUrl: this._options.baseUrl ?? this._options.environment,
                headers: this._options.headers,
                timeoutInSeconds: this._options.timeoutInSeconds,
                maxRetries: this._options.maxRetries,
                fetch: this._options.fetch,
                logging: this._options.logging,
                getAuthHeaders: async () => (await this._options.authProvider.getAuthRequest()).headers,
            },
            requestOptions,
        );
    }
}
