// This file was auto-generated by Fern from our API Definition.

export const OsintCatEnvironment = {
    Production: "https://www.osintcat.net",
} as const;

export type OsintCatEnvironment = typeof OsintCatEnvironment.Production;
